### ISSUE TITLE
Message list appearance

### ISSUE THREAD

**Issue by cketti** [thundernest/k-9#4110]
Right now the message list looks very dated. To move to a more modern look I suggest the following changes:

- [x] For unread messages display subject, sender (and possibly the date) in bold. See #4189
- [x] Don't change the background color for unread messages by default, i.e. make 'General settings > Display > Change colour when read' unchecked by default. See #4128
- [x] Align text (subject, sender, preview) with folder name in the toolbar. See #4177
- [x] Tweak icon to star a message. See #4124
- [x] Remove colored bar at the left that indicates which account a message belongs to. In list views where we mix messages from different accounts we probably still want to show some kind of indicator. See #4177 (change account chip), #4181 (hide chip)
- [x] Increase font size of subject line. See #4116
- [x] Reduce the font size of placeholder contact images a little bit. See #4123
- [x] Use material design colors for contact image placeholders. See #4162 

Experimental things (don't implement before all of the above is done):
- [x] Use more vertical padding for the message list items.
- [ ] ~~Use an outline for the box around the number of messages in a thread to make it less pronounced.~~
- [ ] For read messages use preview text color for subject and sender. That way unread messages stand out even more.
- [x] Experiment with list item divider options: full line, shortened line (see #1859), no line
- [x] Use color for starred messages (see #5512)
- [ ] Experiment with using Roboto Thin as font

If you want to help out with the implementation, please create a pull request that only deals with **one** item from this list. It's much easier to iterate on a pull request if there's only one change at a time.

**Comment by rspencer01** [comment]
Could I also suggest
[ ] Use pastel colours for placeholder contact images
[ ] Shorten grey line between successive messages
to attempt more parity with #1859 (which I presume is the design brief we are heading towards).  

In this vein, I don't think that making the sender and subject preview text colour will be useful.  It will blur the distinction between the subject and the content (in fact it will make it ambiguous as they are just separated by a space) and I feel that if done correctly, bold should be more than enough to show which emails are read and which not.

**Comment by cketti** [comment]
> [ ] Use pastel colours for placeholder contact images

I'd like us to use more material-y colors. But I find the ones from #1859 are too light.

> [ ] Shorten grey line between successive messages

I haven't yet made up my mind on what the list item divider should look like. Full line, shortened line, and no line at all are all options I think could work. I'll experiment with all these options once the other items have been implemented.

> In this vein, I don't think that making the sender and subject preview text colour will be useful. It will blur the distinction between the subject and the content (in fact it will make it ambiguous as they are just separated by a space) and I feel that if done correctly, bold should be more than enough to show which emails are read and which not.

Good point about the border between sender (or subject, depending on settings) and the message content being blurred. Using a dash as divider (like the concept design in #1859) might be a good idea.
I suggested using the same text color because I find it works really well in Gmail.  I'm not set on this approach. So this should probably go into the "experiment" bucket. I've updated the first post.

**Comment by ByteHamster** [comment]
> I'd like us to use more material-y colors. But I find the ones from #1859 are too light.

@cketti What shade of the colors do you prefer? In my opinion, 500 is too "strong". I like 300 or 700 more. 

![tmp_20068](https://user-images.githubusercontent.com/5811634/61999577-b9df2b80-b0c4-11e9-8c7f-6006e962daa2.jpg)

**Comment by cketti** [comment]
@ByteHamster: It probably depends on the color. Yellow 300 or Grey 300 feel too light. We probably also want different shades depending on the theme. Maybe start with 400 for the light theme? 
You could open a new issue where you post screenshots showing different options. That's probably easier than trying to pick suitable colors from a color matrix.

**Comment by bhm** [comment]
> Remove colored bar at the left that indicates which account a message belongs to. In list views where we mix messages from different accounts we probably still want to show some kind of indicator. Suggestions on how to do this without such a bar on the left are very welcome.

Spark has a nice solution to this that should be familiar to the users of k9. 
They use a colored bar in the first line of the message view. First line consist of label icon (mostly autoassigned via ML I presume), colored bar (if in multiinbox), email title.

**Comment by cketti** [comment]
> Spark has a nice solution to this that should be familiar to the users of k9.
> They use a colored bar in the first line of the message view. First line consist of label icon (mostly autoassigned via ML I presume), colored bar (if in multiinbox), email sender. Seems like this language should feel right at home in k9

Sounds interesting. Can you post a screenshot?

**Comment by bhm** [comment]
![image](https://user-images.githubusercontent.com/1051410/62879718-12046780-bd2c-11e9-95e4-a734d7ad0eb4.png)

**Comment by bhm** [comment]
Message details in turn have no account indicator. Which makes sense since they already show the recipient.

**Comment by desrod** [comment]
I'm definitely in the camp that _**does not**_ like the reduced color when viewing messages now. It's changed from a thicker bar to a thin, vertical line of pixels. 

When you've got a dozen different mail accounts in Unified Inbox, it's nearly impossible to tell which messages came into which account anymore. In previous versions, it was very clear. Now it's a lot more difficult, and there doesn't appear to be a way to fix/change/influence it. 

Can we please make this configurable, or revert to the previous behavior? This new look is a _lot_  worse for usability.

**Comment by Donkey-Doug** [comment]
I would like to suggest to romove the horizontal divider line between each message.
