### ISSUE TITLE
Email tracking 

### ISSUE THREAD

**Issue by heberjeur** [thundernest/k-9#6420]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.309

### Problem you are trying to solve

Depending on the situation, it can be super helpful to see when important emails are read. It let me know whether or not my message has been opened.

### Suggested solution

I will get a notification in real-time that someone has viewed or and read my mail.

Like Gmail does by using Mailtrack extensions

**Comment by cketti** [comment]
You can already request read receipts from recipients (select "read receipt" from the menu when composing a message). Whether or not their clients will actually send one is up to them. K-9 Mail currently doesn't support sending read receipts. See #1432.
